import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/molecules/footer/Footer";
import ClientHeader from "./components/molecules/header/ClientHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className="flex h-full flex-col">
        <ClientHeader/>
        <main className="mt-[100px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
